### ISSUE TITLE
Blockhashes all zero duing syncing

### ISSUE THREAD

**Issue by arnuschky** [vtnerd/motrix#5]
![image](https://user-images.githubusercontent.com/179920/107021291-3cf63d00-67a4-11eb-94f1-67a3189af479.png)

```
monerod --version
Monero 'Oxygen Orion' (v0.17.1.7-release)
```

built https://github.com/vtnerd/motrix/commit/163ec8f04c15d6024d54c79f6d6c5b336ecb0446

**Comment by vtnerd** [comment]
Crap, its not fun or cool this way.

Was the progress meter still moving? Or did that stall too? The logic when handling a connection drop is a little tricky because ZMQ hides the actual connection attempts from the main API.

**Comment by arnuschky** [comment]
Progress was moving fine, so the connection was active.

**Comment by vtnerd** [comment]
Ok, I may have reproduced this locally. Check the ZMQ_PUB connection, which is separate from the RPC connection. `monerod` must be started with `--zmq-pub` and `motrix` must match this setting. If the PUB connection fails, it currently does so silently due to ZMQ behavior. The progress meter will still update periodically, because the code will probe the RPC channel if no pub-message was sent after 5 minutes.

I haven't found a quick way to debug whether this is the problem (without a patch), so apologies for the rather brief "check connection" response.

**Comment by vtnerd** [comment]
EDIT above: "if the PUB connection fails" ... a failed RPC connection is very obvious because nothing will work.

**Comment by vtnerd** [comment]
Or wait! Check the connection table from the OS. It should show two established connections - one for RPC and one for PUB.

**Comment by arnuschky** [comment]
Maybe I misunderstood how I start this.

I use `monerod --zmq-pub tcp://127.0.0.1:18084` to start monerod on mainnet.

What should I call motrix with?

**Comment by vtnerd** [comment]
`./motrix tcp://127.0.0.1:18084 tcp://127.0.0.1:18082` assuming both processes are on the same box. If they are on different boxes, then `monerod` is only listening for local connections.

**Comment by vtnerd** [comment]
Its probably synced by now so less fun :/ hopefully still useful.

**Comment by arnuschky** [comment]
Yes that works. Maybe add the command line parameters to the documentation or motrix itself?

It's really pretty, btw! Great job.

**Comment by vtnerd** [comment]
#6 was opened to improve the error reporting.
